language: python

os:
  - linux

dist: bionic

python:
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get install wget
  - wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
  - sudo dpkg --install pandoc-2.7.3-1-amd64.deb

addons:
  apt:
    update: true

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - python -m flask run & pytest


env:
  - PYTHONPATH=.

notifications:
  email: false