language: python

os:
  - linux

dist: bionic

python:
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get install wget
  - wget https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
  - sudo dpkg --install pandoc-2.7.3-1-amd64.deb

addons:
  apt:
    update: true

install:
  - pip install -r requirements-dev.txt

script:
  - pytest --cov=./src tests/

after_success:
  - codecov

env:
  global:
    - PYTHONPATH=.
    - FLASK_APP="src/app.py"
    - secure: "wZwhN30g+qfrrxD66Xi60x4h+0i4SvIWcQH+xcmMM22jZq8YMEH8C5GTZNbAiTvTx0xJYUqdjG8GXhL2gE6WqCrFCffN85+NV9E5yIbjW1Enq72GNji5D6t9/9O7VqqqyDZs1pMvs3TvAKWRkQMlX1uWZd0bzvrEVzKDcm4W2l1GbtS0ghcfD7OWKgJsnlFvwNM4budzY9Fdj1YkGfgobuPSCNMGd/Yasj5XtZVtTF4z5Y9a9bCQ0y8E/VB71Znvj/cGOQ9f82/MypSODoH39CwPlPpdU3iFi2ibuMTBcSJa+wO/Pt6P+XrLZLLD25/FNjiTfz8Ur4wCjCCa4dpOBhoQyOon9Vc/d1W4lCTkuKQvgGBqiL7yeXZOKo+8VXhlzDC5DETUAkR7hyb0CCM6GXySvMvc9L8b4DViF7SrC+QfDWGictWZ8Ta/AZSy3MogznqLYeBXXyfO8H8CUsS0pBuxD7n0rhrCLCb78EtvOEKZ8yRovH30acfPPQtcd4pWTqMZbHerTGDex1wL/Z32kF3ntuezWAU5iSUlF+SSnGyATsZwQ1ffuJOsgGUPBP0QfV4PwuspzAbh3T3Vo3WC7BYzSOkeW+Yb9XWaCcC3nGJzTUDTWMK2t9r+JcrlTjp8/Yf1H80dbz2ldud8p+rfggDwP03N5l76gk7a24pyeQY="

notifications:
  email: false