language: python

os:
  - linux

python:
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get -y install pandoc
addons:
  apt:
    update: true

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - python -m flask run
  - pytest

env:
  - PYTHONPATH=.

notifications:
  email: false